heat_template_version: 2013-05-23

description: |
  This is a Heat template to deploy a standalone redis server on
  Rackspace Cloud Servers


parameters:

  server_flavor:
    description: Rackspace Cloud Server flavor
    type: string
    default: 1 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 512MB Standard Instance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  image_name:
    label: Server Image
    description: Operating system to use for created servers
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr)
    constraints:
    - allowed_values:
      - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 14.04 LTS (Trusty Tahr)
      description: Must be a supported operating system.

  redis_version:
    description: version of redis to install
    type: string
    default: 2.8.9

  redis_hostname:
    description: Hostname for redis server
    type: string
    default: redis

  ssh_keypair_name:
    description: Nova keypair name for ssh access to the servers
    type: string
    default: redis

  redis_port:
    description: port for redis servers to listen on
    type: number
    default: 6379

resources:

  ssh_key:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: ssh_keypair_name }
      save_private_key: true

  redis_password:
    type: OS::Heat::RandomString
    properties:
      length: 32
      sequence: lettersdigits

  redis_server:
    type: Rackspace::Cloud::Server
    depends_on: ssh_key
    properties:
      name: { get_param: redis_hostname }
      flavor: { get_param: server_flavor }
      image: { get_param: image_name }
      key_name: { get_resource: ssh_key }

  redis_server_config:
    type: OS::Heat::ChefSolo
    depends_on: redis_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [redis_server, accessIPv4] }
      kitchen: https://github.com/rackspace-orchestration-templates/redis-single.git
      node:
        run_list: [ "recipe[apt]",
                    "recipe[build-essential]",
                    "recipe[redisio::default]",
                    "recipe[redisio::enable]" ]
        redisio:
          default_settings:
            requirepass: { get_attr: [redis_password, value] }
          servers:
            - name: { get_param: redis_hostname }
              port: { get_param: redis_port }
          version: { get_param: redis_version }

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }
  redis_password:
    value: { get_attr: [redis_password, value] }
  redis_server_ip:
    value: { get_attr: [redis_server, accessIPv4]}
  redis_port:
    value: { get_param: redis_port }
